### PR TITLE
fix: initialize file size

### LINKED ISSUE #34: Current size wrongly initialised to zero
Instead, it should be initialised to the size of the destination file if it exists, zero otherwise.

### PR DESCRIPTION
**Pull request by burgerni10**
The currentSize was initialised to zero, causing the rolling to not happen on restarting the transport.

Fix #34

### CODE REVIEW

File: pino-roll.js [hunk 1]
```diff
@@ -38,15 +38,23 @@ const { buildFileName, detectLastNumber, parseSize, parseFrequency, getNext } =
  * @param {PinoRollOptions} options - to configure file destionation, and rolling rules.
  * @returns {SonicBoom} the Sonic boom steam, usabled as Pino transport.
  */
-module.exports = async function ({ file, size, frequency, extension, ...opts } = {}) {
+module.exports = async function ({
+  file,
+  size,
+  frequency,
+  extension,
+  numberOfFiles,
```
Comment (feugy) [inline pino-roll.js:46]:
```suggestion
```

This seems a new, unused, addition.

**Review by feugy — APPROVED** [review]
Thank you @burgerni10!

**Comment by mcollina** [comment]
@burgerni10 are you still interested in finishing this work? It conflicts right now

**Comment by burgerni10** [comment]
> @burgerni10 are you still interested in finishing this work? It conflicts right now

Hi @mcollina, I've rebased my PR and adapt a test. Since we now retrieve the initial file size, it shifts the log to the next file. I remove one long(number 7) because it would have removed file number 3 (because of the rotation).
